name: AutoNKU

on:
  workflow_dispatch:
  schedule:
    - cron:  0 3 * * * 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Checkin
      run: |
        python3 main.py 
      env: 
        PHPSESSID: ${{ secrets.PHPSESSID }}
        q14: ${{ secrets.q14 }}
        q15: ${{ secrets.q15 }}
