name: AutoNKU

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 3 * * * 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python3 main.py 
      env: 
        COOKIE: ${{ secrets.COOKIE }}
        SCON: ${{ secrets.SCON }}
        SCKEY: ${{ secrets.SCKEY }}
        ROOMID: ${{ secrets.ROOMID }}
